primary_person_path: "./Data/Primary_Person_use.csv"     
units_use_path: "Data/Units_use.csv"
damages_path: "Data/Damages_use.csv"
Endorse: "Data/Endorse_use.csv"
charges_path: "Data/Charges_use.csv"
Restrict: "Data/Restrict_use.csv"
analysis_1_output: "outputs/no_of_acc_male_deaths"
analysis_2_output: "outputs/no_of_two_wheelers" 
analysis_3_output: "outputs/top_five_vehicles"
analysis_4_output: "outputs/valid_drivers_license_hnr"
analysis_5_output: "outputs/highest_no_female_accident_states"
analysis_6_output: "outputs/top_veh_make_ids"
analysis_7_output: "outputs/top_ethnicity"
analysis_8_output: "outputs/top_alcohol_crash_zip"
analysis_9_output: "outputs/no_damages_insurance"
analysis_10_output: "outputs/top_5_vehicles_speeding"
output_text_file: "outputs/output.txt"

spark_config:
  master: "local[*]"                 
  app_name: "Vehicle Accidents Analysis Case Study"
  executor_memory: "2g"
  driver_memory: "2g"
